
import FileManager.FileManager;
import javax.swing.JOptionPane;
import dataController.Controller;
import helper.Helper;
import java.util.List;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sai Lin Htet
 */
public class Form extends javax.swing.JFrame {
    String[] userInfo=new String[12];
    /**
     * Creates new form NewJFrame
     */
    public Form(String[] userInfo) {
        this.userInfo[0]=userInfo[0];
        this.userInfo[1]=userInfo[1];
        this.userInfo[2]=userInfo[2];
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _GenderGp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        _age = new javax.swing.JSlider();
        _maleRB = new javax.swing.JRadioButton();
        _femaleRB = new javax.swing.JRadioButton();
        _otherRB = new javax.swing.JRadioButton();
        _zodic = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        _height = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _age_value = new javax.swing.JLabel();
        _phone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        _name = new javax.swing.JTextField();
        weight = new javax.swing.JLabel();
        _weight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        _bio = new javax.swing.JTextArea();
        _submit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        _hobby = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        _age.setMaximum(60);
        _age.setMinimum(16);
        _age.setValue(16);
        _age.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _age.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                _ageStateChanged(evt);
            }
        });

        _GenderGp.add(_maleRB);
        _maleRB.setText("Male");
        _maleRB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _GenderGp.add(_femaleRB);
        _femaleRB.setText("Female");
        _femaleRB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _GenderGp.add(_otherRB);
        _otherRB.setText("Other");
        _otherRB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _zodic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces" }));

        jLabel1.setText("Fill Your Information");

        jLabel2.setText("Name");

        _height.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                _heightInputMethodTextChanged(evt);
            }
        });
        _height.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                _heightKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _heightKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                _heightKeyTyped(evt);
            }
        });

        jLabel3.setText("Age");

        jLabel4.setText("Gender");

        jLabel5.setText("Zodic");

        _age_value.setText("16");

        _phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _phoneFocusLost(evt);
            }
        });

        jLabel7.setText("Phone");

        jLabel8.setText("Height");

        jLabel9.setText("cm");

        weight.setText("Weight");

        _weight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _weightKeyReleased(evt);
            }
        });

        jLabel10.setText("kg");

        _bio.setColumns(20);
        _bio.setRows(5);
        jScrollPane1.setViewportView(_bio);

        _submit.setText("Submit");
        _submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _submitActionPerformed(evt);
            }
        });

        jLabel11.setText("Bio");

        jLabel12.setText("Hobby");

        _hobby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reading", "Painting", "Cycling", "Hiking", "Photography", "Yoga", "Gaming", "Running", "Gardening", "Music", "Baking", "Swimming", "Writing", "Chess", "Cooking", "Board Games", "Dancing", "Travel", "Drawing", "Camping", "Knitting", "Kayaking", "Puzzles", "Crafts", "Walking", "Woodworking", "Volunteering", "Makeup", "Tennis", "Skiing", "Piano", "Climbing", "Calligraphy", "Fishing", "Gym", "Art", "Singing", "Sketching", "Sewing", "Decor crafting", "Coding" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(55, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(_maleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(_femaleRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(_otherRB))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(_age, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(_age_value))
                                    .addComponent(_phone)
                                    .addComponent(_name)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(_zodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_height, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(weight)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(_weight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)))))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(_submit)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(_age_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_otherRB)
                    .addComponent(jLabel4)
                    .addComponent(_maleRB)
                    .addComponent(_femaleRB))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(_zodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(weight)
                    .addComponent(_weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(_submit)
                .addGap(57, 57, 57))
        );

        _age.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__submitActionPerformed
        // TODO add your handling code here:
        String name=_name.getText();
        String age= String.valueOf(_age.getValue());
        String gender=_maleRB.isSelected()? "Male":_femaleRB.isSelected()? "Female":_otherRB.isSelected()? "Other":"";
        String phone=_phone.getText();
        String zodic=_zodic.getSelectedItem().toString();
        String hobby=_hobby.getSelectedItem().toString();
        String height=_height.getText();
        String weight=_weight.getText();
        String bio=_bio.getText();

        if(Helper.isEmpty(name)|| Helper.isEmpty(age)||Helper.isEmpty(gender)|| Helper.isEmpty(phone)||Helper.isEmpty(height)||Helper.isEmpty(weight)){
            JOptionPane.showMessageDialog(this, "Please fill all imformation!!","Can't Submit Form",HEIGHT);
        }else{
           this.userInfo[3]=name;
           this.userInfo[4]=gender;
           this.userInfo[5]=phone;
           this.userInfo[6]=age;
           this.userInfo[7]=zodic;
          this.userInfo[8]=height;
          this.userInfo[9]=weight;
          this.userInfo[10]=hobby;
          this.userInfo[11]=bio;
        try {
           FileManager.updateUser(this.userInfo);
           Home home=new Home(this.userInfo);
            setVisible(false);
            home.setVisible(true);
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.exit(0);
        }  
        }
    }//GEN-LAST:event__submitActionPerformed

    private void _ageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event__ageStateChanged
        // TODO add your handling code here:
        _age_value.setText(String.valueOf(_age.getValue()));
    }//GEN-LAST:event__ageStateChanged

    private void _heightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__heightKeyReleased
        // TODO add your handling code here:
        try {
        int height = Integer.parseInt(_height.getText());
        if (!(height >= 0 && height <= 300)) {
            JOptionPane.showMessageDialog(this, "Height must be between 0 and 300!!!", "Invalid Height", HEIGHT);
            _height.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Height must be digits!!!");
        _height.setText("");
    }
    }//GEN-LAST:event__heightKeyReleased

    private void _weightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__weightKeyReleased
        // TODO add your handling code here:
        try {
        int weight = Integer.parseInt(_weight.getText());
        if (!(weight >= 0 && weight <= 500)) {
            JOptionPane.showMessageDialog(this, "Weight must be between 0 and 500!!!", "Invalid Weight", HEIGHT);
            _weight.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Weight must be digits!!!");
        _weight.setText("");
    }
    }//GEN-LAST:event__weightKeyReleased

    private void _phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__phoneFocusLost
        // TODO add your handling code here:
                try {
         Integer.parseInt(_phone.getText());
        if (!(_phone.getText().length()<=11 && _phone.getText().length()>=6)) {
            JOptionPane.showMessageDialog(this, "Phone number must have at least 6 digits!!!", "Invalid Height", HEIGHT);
            _phone.setText("");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Phone number must be digits!!!");
        _phone.setText("");
    }
    }//GEN-LAST:event__phoneFocusLost

    private void _heightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__heightKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event__heightKeyTyped

    private void _heightKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__heightKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event__heightKeyPressed

    private void _heightInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event__heightInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event__heightInputMethodTextChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _GenderGp;
    private javax.swing.JSlider _age;
    private javax.swing.JLabel _age_value;
    private javax.swing.JTextArea _bio;
    private javax.swing.JRadioButton _femaleRB;
    private javax.swing.JTextField _height;
    private javax.swing.JComboBox<String> _hobby;
    private javax.swing.JRadioButton _maleRB;
    private javax.swing.JTextField _name;
    private javax.swing.JRadioButton _otherRB;
    private javax.swing.JTextField _phone;
    private javax.swing.JButton _submit;
    private javax.swing.JTextField _weight;
    private javax.swing.JComboBox<String> _zodic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
