
import FileManager.FileManager;
import javax.swing.JOptionPane;
import dataController.Controller;
import helper.Helper;
import java.io.IOException;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this licensez
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sai Lin Htet
 */
public class Home extends javax.swing.JFrame {
    Helper helper=new Helper();
    String[] userInfo=new String[12];
    /**
     * Creates new form NewJFrame
     */
    public Home(String[] userInfo) {
        this.userInfo=userInfo.clone();

        initComponents();
        _resultList.setLayout(new BoxLayout(_resultList, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _GenderGp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        _age = new javax.swing.JSlider();
        _maleRB = new javax.swing.JRadioButton();
        _femaleRB = new javax.swing.JRadioButton();
        _otherRB = new javax.swing.JRadioButton();
        _zodic = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        _minHeight = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _age_value = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        _maxWeight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        _search = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        _hobby = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        _minWeight = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        _maxHeight = new javax.swing.JTextField();
        _home = new javax.swing.JButton();
        _profile = new javax.swing.JButton();
        _result = new javax.swing.JLabel();
        _ListScroll = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        _resultList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        _age.setMaximum(60);
        _age.setMinimum(16);
        _age.setValue(16);
        _age.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _age.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                _ageStateChanged(evt);
            }
        });

        _GenderGp.add(_maleRB);
        _maleRB.setText("Male");
        _maleRB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _GenderGp.add(_femaleRB);
        _femaleRB.setText("Female");
        _femaleRB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _GenderGp.add(_otherRB);
        _otherRB.setText("Other");
        _otherRB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _zodic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces" }));

        jLabel1.setText("Find Your Soulmate");

        _minHeight.setText("0");
        _minHeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _minHeightFocusLost(evt);
            }
        });
        _minHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _minHeightKeyReleased(evt);
            }
        });

        jLabel3.setText("Age");

        jLabel4.setText("Gender");

        jLabel5.setText("Zodic");

        _age_value.setText("16");

        jLabel8.setText("Height");

        jLabel9.setText("cm");

        weight.setText("Weight");

        _maxWeight.setText("300");
        _maxWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _maxWeightKeyReleased(evt);
            }
        });

        jLabel10.setText("kg");

        _search.setText("Search");
        _search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _searchActionPerformed(evt);
            }
        });

        jLabel12.setText("Hobby");

        _hobby.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Reading", "Painting", "Cycling", "Hiking", "Photography", "Yoga", "Gaming", "Running", "Gardening", "Music", "Baking", "Swimming", "Writing", "Chess", "Cooking", "Board Games", "Dancing", "Travel", "Drawing", "Camping", "Knitting", "Kayaking", "Puzzles", "Crafts", "Walking", "Woodworking", "Volunteering", "Makeup", "Tennis", "Skiing", "Piano", "Climbing", "Calligraphy", "Fishing", "Gym", "Art", "Singing", "Sketching", "Sewing", "Decor crafting", "Coding" }));

        jLabel11.setText("-");

        _minWeight.setText("0");
        _minWeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _minWeightKeyReleased(evt);
            }
        });

        jLabel13.setText("-");

        _maxHeight.setText("300");
        _maxHeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                _maxHeightFocusLost(evt);
            }
        });
        _maxHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                _maxHeightKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_minHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_maxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(weight)
                        .addGap(12, 12, 12)
                        .addComponent(_minWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_maxWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_search))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_maleRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_femaleRB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_otherRB))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_zodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_age, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_age_value)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(_age_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(_maleRB)
                    .addComponent(_femaleRB)
                    .addComponent(_otherRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(_zodic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(_hobby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(_minHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(_maxHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(weight)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(_minWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(_maxWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel13)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(_search)
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        _age.getAccessibleContext().setAccessibleName("");

        _home.setText("Home");
        _home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        _profile.setText("Profile");
        _profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        _profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _profileActionPerformed(evt);
            }
        });

        _result.setText("Result");

        javax.swing.GroupLayout _resultListLayout = new javax.swing.GroupLayout(_resultList);
        _resultList.setLayout(_resultListLayout);
        _resultListLayout.setHorizontalGroup(
            _resultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        _resultListLayout.setVerticalGroup(
            _resultListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(_resultList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_resultList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        _ListScroll.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(_ListScroll)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(_home)
                                    .addComponent(_profile)))
                            .addComponent(_result))
                        .addGap(87, 87, 87)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_profile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(_result)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_ListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__profileActionPerformed
        // TODO add your handling code here:
        Profile profile=new Profile(this.userInfo);
        setVisible(false);
        profile.setVisible(true);
    }//GEN-LAST:event__profileActionPerformed

    private void _maxHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__maxHeightKeyReleased
        // TODO add your handling code here:
        try {
            int height = Integer.parseInt(_maxHeight.getText());
            if (!(height >= 0 && height <= 300)) {
                JOptionPane.showMessageDialog(this, "Height must be between 0 and 300!!!", "Invalid Height", HEIGHT);
                _maxHeight.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Height must be digits!!!");
            _minHeight.setText("");
        }
    }//GEN-LAST:event__maxHeightKeyReleased

    private void _minWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__minWeightKeyReleased
        // TODO add your handling code here:
        try {
            int height = Integer.parseInt(_minWeight.getText());
            if (!(height >= 0 && height <= 300)) {
                JOptionPane.showMessageDialog(this, "Height must be between 0 and 300!!!", "Invalid Height", HEIGHT);
                _minWeight.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Height must be digits!!!");
            _minHeight.setText("");
        }
    }//GEN-LAST:event__minWeightKeyReleased

    private void _maxWeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__maxWeightKeyReleased
        // TODO add your handling code here:
        try {
            int weight = Integer.parseInt(_maxWeight.getText());
            if (!(weight >= 0 && weight <= 500)) {
                JOptionPane.showMessageDialog(this, "Weight must be between 0 and 500!!!", "Invalid Weight", HEIGHT);
                _maxWeight.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Weight must be digits!!!");
            _maxWeight.setText("");
        }
    }//GEN-LAST:event__maxWeightKeyReleased

    private void _minHeightKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event__minHeightKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event__minHeightKeyReleased

    private void _ageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event__ageStateChanged
        // TODO add your handling code here:
        _age_value.setText(String.valueOf(_age.getValue()));
    }//GEN-LAST:event__ageStateChanged

    private void _searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__searchActionPerformed
        // TODO add your handling code here:

        String age= String.valueOf(_age.getValue());
        String gender=_maleRB.isSelected()? "Male":_femaleRB.isSelected()? "Female":_otherRB.isSelected()? "Other":"";
        String zodic=_zodic.getSelectedItem().toString();
        String hobby=_hobby.getSelectedItem().toString();
        int minHeight= Integer.parseInt(_minHeight.getText());
        int maxHeight=Integer.parseInt(_maxHeight.getText());
        int minWeight=Integer.parseInt(_minWeight.getText());
        int maxWeight=Integer.parseInt(_maxWeight.getText());

        try {
            List<String[]> userList = FileManager.getAllUser();
            List<String[]> result = Controller.findvalueFromArr(userList, "age", age,new Integer[]{});
            if(!(gender.isEmpty())){
                result = Controller.findvalueFromArr(result, "gender", gender,new Integer[]{});
            }
            if(!(zodic.equals("All"))){
                result = Controller.findvalueFromArr(result, "zodiac sign", zodic,new Integer[]{});
            }if(!(hobby.equals("All"))){
                result = Controller.findvalueFromArr(result, "hobby", hobby,new Integer[]{});
            }
            if(!(_minHeight.getText().isEmpty() &&_maxHeight.getText().isEmpty())){
                result = Controller.findvalueFromArr(result, "height", "",new Integer[]{minHeight, maxHeight});
            }if(!(_minWeight.getText().isEmpty() && _maxWeight.getText().isEmpty())){
                result = Controller.findvalueFromArr(result, "weight", "",new Integer[]{minWeight, maxWeight});
            }
            _resultList.removeAll();
            if (result.size() != 0) {
                for(int i=0;i<result.size();i++){
                    
                JPanel userCard=helper.createCrad(result.get(i));
                _resultList.add(userCard);
                _resultList.revalidate();
                _resultList.repaint();
                }
               
            }else{
                JOptionPane.showMessageDialog(this, "Username or Password is not correct.", "Can't Login", HEIGHT);
            }

        } catch (IOException e) {
            System.out.println(e.getMessage());
            System.exit(0);
        }

    }//GEN-LAST:event__searchActionPerformed

    private void _minHeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__minHeightFocusLost
        // TODO add your handling code here:
                try {
            int height = Integer.parseInt(_minHeight.getText());
            if (!(height >= 0 && height <= 300)) {
                JOptionPane.showMessageDialog(this, "Height must be between 0 and 300!!!", "Invalid Height", HEIGHT);
                _minHeight.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Height must be digits!!!");
            _minHeight.setText("");
        }
    }//GEN-LAST:event__minHeightFocusLost

    private void _maxHeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event__maxHeightFocusLost
        // TODO add your handling code here:
                try {
            int height = Integer.parseInt(_maxHeight.getText());
            if (!(height >= 0 && height <= 300)) {
                JOptionPane.showMessageDialog(this, "Height must be between 0 and 300!!!", "Invalid Height", HEIGHT);
                _maxHeight.setText("300");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Height must be digits!!!");
            _minHeight.setText("");
        }
    }//GEN-LAST:event__maxHeightFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup _GenderGp;
    private javax.swing.JScrollPane _ListScroll;
    private javax.swing.JSlider _age;
    private javax.swing.JLabel _age_value;
    private javax.swing.JRadioButton _femaleRB;
    private javax.swing.JComboBox<String> _hobby;
    private javax.swing.JButton _home;
    private javax.swing.JRadioButton _maleRB;
    private javax.swing.JTextField _maxHeight;
    private javax.swing.JTextField _maxWeight;
    private javax.swing.JTextField _minHeight;
    private javax.swing.JTextField _minWeight;
    private javax.swing.JRadioButton _otherRB;
    private javax.swing.JButton _profile;
    private javax.swing.JLabel _result;
    private javax.swing.JPanel _resultList;
    private javax.swing.JButton _search;
    private javax.swing.JComboBox<String> _zodic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
